### ISSUE TITLE
Не пашет. Залипуха. - doesn't build?

### ISSUE THREAD

**Issue by DevirPlatform** [praeclarum/Netjs#15]

**Comment by praeclarum** [comment]
I am working on upgrading the build system. Hopefully it will fix it for you. Can you post the error?

**Comment by praeclarum** [comment]
Ah I just got a better translation: https://twitter.com/KirillOsenkov/status/958844833275129857

Yeah there are lots of limitations of the library. Please open a new bug with any error it gives you or what's happening in your app.
